AWSTemplateFormatVersion: '2010-09-09'
Description: Example simple web application environment

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-simple-bucket-coding-hour-11223344 # Change the number suffix to something globally unique.

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08982f1c5bf93d976  # Update with the latest Amazon Linux 2 AMI ID.
      KeyName: my-key-pair  # Replace with your key pair name.
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and MySQL access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # SSH access
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0  # MySQL access
